# what's output of this code


```go
func aaa() (done func(), err error) {
 return func() { 
   print("aaa: done") 
 }, nil
}

func bbb() (done func(), _ error) {
 done, err := aaa()
 return func() { 
   print("bbb: surprise!"); 
   done() 
 }, err
}

func main() {
 done, _ := bbb()
 done()
}
```

## 分析程序

缩小范围，核心关注到这块代码。如下：

```go
func bbb() (done func(), _ error) {
 done, err := aaa()
 return func() { 
   print("bbb: surprise!")
   done() 
 }, err
}
```

在最后一行的这个闭包（匿名函数）中，大家可能认为程序调用了函数 aaa 所返回的 done 值来输出程序，应当是：

```go
aaa: done
```

这个想法是错误的，程序没有这么去运作。

原因在于 return 实际上是一个赋值语句。结合程序，可以看到函数 bbb 的第一个返回值是 done 参数。

```go
func bbb() (done func(), _ error)
```

也就是在函数 bbb 在程序最后执行 return 语句后，会对返回变量 done 进行赋值，自然该值不会是由函数 aaa 所设置的了。

这是一个关键的地方。


## 具体过程

这个程序输出结果是什么呢？

他会不断地递归，疯狂输出 “bbb: surprise!”，直至栈溢出，导致程序运行出错，最终中止

同学就疑惑了，怎么又多出了个递归？

我们再看看程序：

```go
func main() {
 done, _ := bbb()
 done()
}

func bbb() (done func(), _ error) {
 ...
 return func() { 
   print("bbb: surprise!"); 
   done() 
 }, err
}
```

本质上在函数 bbb 执行完毕后， 变量 done 已经变成了一个递归函数。

递归的过程是：函数 bbb 调用变量 done 后，会输出 bbb: surprise! 字符串，然后又调用变量 done。而变量 done 又是这个闭包（匿名函数），从而实现不断递归调用和输出。